name: 'Advanced Issue Triage'
description: 'A smart issue triage action for GitHub repositories.'
author: 'yaouDev / August Jansson'
branding:
    icon: 'alert-circle'
    color: 'green'

inputs:
  
  config-path:
    description: 'The path to your JSON-file containing labels, assignees, etc.'
    required: true
    default: 'issue-config.json'

  stale-days:
    description: 'Number of days an issue can be inactive before being marked as stale. Set to 0 to disable.'
    required: false
    default: '30'
  
  close-days:
    description: 'Number of days to wait after an issue is marked as stale before closing it. Set to 0 to disable.'
    required: false
    default: '7'
  
  stale-message:
    description: 'The comment to add when an issue is marked as stale.'
    required: false
    default: 'This issue is stale because it has been open for {{ stale-days }} days with no activity. Remove the stale label or comment, otherwise this issue will be closed in {{ close-days }} days.'

  close-message:
    description: 'The comment to add when an issue is closed automatically.'
    required: false
    default: 'This issue was closed because it has been inactive for a long time. Please reopen if this issue is still relevant.'

  issue-index:
    description: 'An optional forced issue number'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  # bash acts weird with kebab-case so we'll make the inputs env variables
  env:
    ASSIGNMENT_RULES: ${{ inputs.assignment-rules }}
    STALE_DAYS: ${{ inputs.stale-days }}
    CLOSE_DAYS: ${{ inputs.close-days }}
    STALE_MESSAGE: ${{ inputs.stale-message }}
    CLOSE_MESSAGE: ${{ inputs.close-message }}
    DEFAULT_ASSIGNEE: ${{ inputs.default-assignee }}
    ISSUE_INDEX: ${{ inputs.issue-index }}
    CONFIG_PATH: ${{ inputs.config-path }}