name: 'Test Issue Triage'

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Issue Title'
        required: true
        default: 'Test: A new bug was found'
      body:
        description: 'Issue Body'
        required: true
        default: 'Steps to reproduce: ... Expected behavior: ...'

jobs:
  test_triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create a dummy issue
        id: create_issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=$(gh issue create --title "${{ github.event.inputs.title }}" --body "${{ github.event.inputs.body }}" --repo ${{ github.repository }} --json number | jq -r .number)
          echo "Created issue #$ISSUE_NUMBER"
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
      
      - name: Run Advanced Issue Triage on the created issue
        uses: yaouDev/issue-triage@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignment-rules: |
            [
              {
                "keywords": "bug,error",
                "assignees": "user1,user2"
              },
              {
                "keywords": "test",
                "assignees": "your-username"
              }
            ]
      
      - name: Clean up the dummy issue
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Closing the dummy issue..."
          gh issue close ${{ steps.create_issue.outputs.issue_number }}
