name: Triage Test

on:
  workflow_dispatch:

jobs:
  simulate-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GitHub CLI (cross-distro safe)
        run: |
            curl -fsSL https://cli.github.com/install.sh | sudo bash

      - name: Simulate test issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create --title "Bug: App crashes on load" --body "There’s a crash when launching the app. Error: segmentation fault"
          gh issue create --title "Feature: Add dark mode" --body "It would be great to have a dark mode. This is a feature request."
          gh issue create --title "Question: What is the update interval?" --body "how to change the refresh rate?"
          gh issue create --title "Short issue" --body "Bug!"
          gh issue create --title "Docs: Clarify setup" --body "The documentation on setup is unclear. Please improve docs."
          gh issue create --title "Enhancement: Optimize memory usage" --body "Feature request to reduce RAM consumption."
          gh issue create --title "Security vulnerability found" --body "This is a critical security flaw in token handling."
          gh issue create --title "Combination: Bug and Feature" --body "App crashes, but I also want new themes."

          echo "Waiting for GitHub to register the issues..."
          sleep 15


  triage:
    runs-on: ubuntu-latest
    needs: simulate-issues
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Issue Triage
        uses: yaouDev/issue-triage@main
        with:
          stale-days: '30'
          close-days: '7'
          stale-message: 'This issue is stale because it has been open for {{ stale-days }} days with no activity. Remove the stale label or comment, otherwise this issue will be closed in {{ close-days }} days.'
          close-message: 'This issue was closed because it has been inactive for a long time. Please reopen if this issue is still relevant.'
          assignment-rules: |
            [
              {
                "keywords": "bug,error,crash,segmentation fault",
                "assignees": "yaouDev"
              },
              {
                "keywords": "feature,enhancement,request",
                "assignees": "yaouDev"
              },
              {
                "keywords": "documentation,docs",
                "assignees": "yaouDev"
              },
              {
                "keywords": "question,how to,what is",
                "assignees": "yaouDev"
              },
              {
                "keywords": "security,critical",
                "assignees": "yaouDev"
              }
            ]
          default-assignee: 'yaouDev'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
